### ISSUE TITLE
failed to access main UI 

### ISSUE THREAD

**Issue by misakayuuki** [menchelab/VRNetzer#1]
failed to access main UI by routating left hand(using quest2 and connect to computer through virtual desktop)

**Comment by misakayuuki** [comment]
sorry i just solve it by enable left hand mode

**Comment by unfriend** [comment]
Nice fix, just tried it myself and I assume you mean using it with the oculus steam vr mode. It might be possible that the hands are switched on startup since the main development platform we use is the HTC vive where the controllers are the same for both hands.
Anyway happy to hear it works for you now, let us know if you need anything else.
